### ISSUE TITLE
Wildcard instead of GraphQL?

### ISSUE THREAD

**Issue by brillout** [watscho/express-graphql-mongodb-boilerplate#108]
Hi @watscho!

I'm curious, what do you think of using [Wildcard API](https://github.com/reframejs/wildcard-api#readme) instead of GraphQL?

As far as I can tell, Wildcard would be a better fit. What do you think?

**Comment by watscho** [comment]
i don't use Wildcard API sorry

**Comment by brillout** [comment]
Any reason you use GraphQL?

**Comment by brillout** [comment]
I'm asking because RPC tools such as Wildcard API are usually a better fit as long as there is no need for third-party developers to be able to access the data. Which is the case for your boilerplate. So I'm wondering if there is a reason why you went for GraphQL.
