### ISSUE TITLE
Authorisation in Tags but not a single Authorisation thing in Boilerplate !!! 

### ISSUE THREAD

**Issue by mrfambo** [watscho/express-graphql-mongodb-boilerplate#109]
Alas!! You added Authorisation tag in Repo but there seems to be missing authorisation support !!!

**Comment by watscho** [comment]
sorry i’m so busy (((

**Comment by watscho** [comment]
https://github.com/watscho/express-graphql-mongodb-boilerplate/blob/master/src/middleware/authentication.js

https://github.com/watscho/express-graphql-mongodb-boilerplate/blob/master/src/module/auth/resolvers.js 

really?
